### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by djeang** [jerkar/protobuf-plugin#1]
Yiou can remove a section from Readme.md 

You don't need to a method  

```
public void doProtobuf() {
    protobuf();
}
```
if you have already
```
public void protobuf() {
    .....
}
```
The doXxxx  convention is for life cycle method. Exemple doTest do everything needed before test : clean + compile + test.

**Comment by cuchaz** [comment]
fixed in de49390cfdf011aff680e08bf356dff9ca6b4cfe
