### ISSUE TITLE
move default sources to /src/main/proto

### ISSUE THREAD

**Issue by djeang** [jerkar/protobuf-plugin#2]
Jerkar follows the Maven dir convention. 
I know it may be controvertial but to be consistant with the other part of Jerkar, default location for .proto files should be /src/main/proto

**Comment by cuchaz** [comment]
fixed in de49390cfdf011aff680e08bf356dff9ca6b4cfe

I personally don't use the maven conventions, but we might as well make the plugin defaults consistent with the jerkar/maven conventions.
