### ISSUE TITLE
Depend on a released version of Jerkar.

### ISSUE THREAD

**Issue by djeang** [jerkar/protobuf-plugin#5]
I will do a Jerkar release very soon so we can depend on it as soon as published. I'll try to publish protobuf plugin as well but in a lower version.
May I suggest to use 0.5 or so ?

**Comment by djeang** [comment]
I've just released 0.4.6 so your plugin build can depend on it as soon as it will be published to OSSRH (few hours/days).

**Comment by djeang** [comment]
Ok, I did it and published this plugin in Maven central. Should be available pretty soon woooa :-)

**Comment by cuchaz** [comment]
Woo! exciting! Thanks. =)
